# https://github.com/tmuxinator/tmuxinator

name: default
root: ~/

windows:
  - "":
  - "":
  - dropbox:
      root: ~/Dropbox
  - repl:
      - workon math
      - ipython
  - ws:
      - mkws
      - cdws
